name: Deploy Laravel Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@3

      - name: Set up SSH agent
        uses: appleboy/ssh-action@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Deploy to EC2
        uses: deployphp/action@v1
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            composer install --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:cache
            sudo systemctl reload nginx

        env:
          GITHUB_WORKSPACE: ${{ github.workspace}}
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
